export const deviceActions = {
  CONNECTION_CHANGE: 'CONNECTION_CHANGE',
  RESET_DEVICE: 'RESET_DEVICE',
};

export const authActions = {
  AUTH_LOGIN_PAYLOAD: 'AUTH_LOGIN_PAYLOAD',
  AUTH_MARCHANT_CREATED: 'AUTH_MARCHANT_CREATED',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
};

export const cartActions = {
  CART_ADD: 'CART_ADD',
  CART_REMOVE: 'CART_REMOVE',
  CART_UPDATE: 'CART_UPDATE',
  CART_UPDATE_REMARK: 'CART_UPDATE_REMARK',
  CART_CLEAR: 'CART_CLEAR',
};
